import java.util.ArrayList;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leo
 */
public class ComprobacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form ComprobacionNumerica
     */
    public ComprobacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComprobar = new javax.swing.JButton();
        lblTemNumero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumero = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt5 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 45, 62));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprobar.setText("Calcular");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        lblTemNumero.setText("Numero");
        getContentPane().add(lblTemNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 20));

        jScrollPane1.setViewportView(txtNumero);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 127, -1));

        jLabel1.setText("Entrada de un numero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jScrollPane2.setViewportView(txt1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 240, 40));

        jScrollPane3.setViewportView(txt2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 240, 40));

        jScrollPane4.setViewportView(txt3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 240, 50));

        jScrollPane5.setViewportView(txt4);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 240, 50));

        jScrollPane6.setViewportView(txt5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 240, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 20, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed

    int num = Integer.parseInt(txtNumero.getText());
     if (num >= 1 && num <= 500) {
    int Divisores = 0;
    for (int n = 1; n < num; n++) {
        if (num % n == 0) {
            Divisores = Divisores + n;
        }
    }
    
    if (Divisores == num) {
             txt1.setText ("El numero  " + txtNumero.getText() + "  es perfecto");
    } else {
             txt1.setText ("El numero  " + txtNumero.getText() + "  no es perfecto");
    }

    if (Primo(  num)) {
         txt2.setText ("El numero  " + txtNumero.getText() + "  es primo");
    } else {
         txt2.setText ("El numero  " + txtNumero.getText() + "  no es primo");
    }
    
    ArrayList<Integer> primosM = new ArrayList<>();
    for (int n = 2; n < num; n++) {
        if (Primo(n)) {
            primosM.add(n);   //solo los números primos se agregarán a la lista.
        }
    }
     txt3.setText ("Los primos menores del numero:  " + txtNumero.getText()+"  son :  " +  primosM );      
     
        int sumaPrimos = 0;
        for (int i = 0; i < primosM.size(); i++) {   // .size : obtener la cantidad de elementos en una colección o lista
            int primo = primosM.get(i);
            sumaPrimos = sumaPrimos+ primo;
        }
     txt4.setText ("La sumatoria de los numeros primos menores es de: " + sumaPrimos);
   
    double raizPrimos = Math.sqrt(sumaPrimos);  //Math.sqrt es una función que calcula la raíz cuadrada de un número
    txt5.setText("La raiz de la sumatoria de los numeros primos menores es de: " + raizPrimos);

     } else{
         JOptionPane.showMessageDialog(rootPane, "Ingrese un numero entre el 1 y el 500");   
           
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    
    
    
    public boolean Primo(int numP) {
    if (numP <= 1) {
        return false;
    }
    for (int n = 2; n * n <= numP; n++) {
        if (numP % n == 0) {
            return false;
        }
    }
    return true;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTemNumero;
    private javax.swing.JTextPane txt1;
    private javax.swing.JTextPane txt2;
    private javax.swing.JTextPane txt3;
    private javax.swing.JTextPane txt4;
    private javax.swing.JTextPane txt5;
    private javax.swing.JTextPane txtNumero;
    // End of variables declaration//GEN-END:variables
}
